image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 9 x64
  - git config --file=.gitmodules submodule.bitfocus-skeleton.url https://github.com/bitfocus/bitfocus-skeleton.git
  - git config --file=.gitmodules submodule.bitfocus-libs.url https://github.com/bitfocus/bitfocus-libs.git
  - git submodule sync
  - git submodule init
  - git submodule update
  - cmd: bash tools/yarn.sh
  - cmd: bash tools/build_writefile.sh
  - yarn

environment:
  TRAVIS_OS_NAME: win64

artifacts:
  - path: electron-output/*.exe
    name: Installer

build_script:
  - yarn windist
  - cmd: bash tools/build_rename_git.sh

test: off

# deploy section to github releases
deploy:
  - provider: GitHub
    artifact: electron-output/*.exe
    draft: false
    prerelease: false
    description: "Release {APPVEYOR_REPO_TAG_NAME}"
    on:
      branch:
        - 1.4.0-backport
      appveyor_repo_tag: true
